# 2. Multiple Linear Regression

### 원-핫 인코딩


In [1]:

import pandas as pd
dataset = pd.read_csv("MultipleLinearRegressionData.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
X

array([[0.5, 3, 'Home'],
       [1.2, 4, 'Library'],
       [1.8, 2, 'Cafe'],
       [2.4, 0, 'Cafe'],
       [2.6, 2, 'Home'],
       [3.2, 0, 'Home'],
       [3.9, 0, 'Library'],
       [4.4, 0, 'Library'],
       [4.5, 5, 'Home'],
       [5.0, 1, 'Cafe'],
       [5.3, 2, 'Cafe'],
       [5.8, 0, 'Cafe'],
       [6.0, 3, 'Library'],
       [6.1, 1, 'Cafe'],
       [6.2, 1, 'Library'],
       [6.9, 4, 'Home'],
       [7.2, 2, 'Cafe'],
       [8.4, 1, 'Home'],
       [8.6, 1, 'Library'],
       [10.0, 0, 'Library']], dtype=object)

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# ('encoder', 원핫 인코더의 첫번째 컬럼을 드롭하겠다, [2]번 컬럼에 대해서 적용하겠다), 나머지는 그대로 두겠다 = passthrough
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='first'), [2])], remainder='passthrough')
X = ct.fit_transform(X)
X

# 1 0 : Home
# 0 1 : Library
# 0 0 : Cafe

array([[1.0, 0.0, 0.5, 3],
       [0.0, 1.0, 1.2, 4],
       [0.0, 0.0, 1.8, 2],
       [0.0, 0.0, 2.4, 0],
       [1.0, 0.0, 2.6, 2],
       [1.0, 0.0, 3.2, 0],
       [0.0, 1.0, 3.9, 0],
       [0.0, 1.0, 4.4, 0],
       [1.0, 0.0, 4.5, 5],
       [0.0, 0.0, 5.0, 1],
       [0.0, 0.0, 5.3, 2],
       [0.0, 0.0, 5.8, 0],
       [0.0, 1.0, 6.0, 3],
       [0.0, 0.0, 6.1, 1],
       [0.0, 1.0, 6.2, 1],
       [1.0, 0.0, 6.9, 4],
       [0.0, 0.0, 7.2, 2],
       [1.0, 0.0, 8.4, 1],
       [0.0, 1.0, 8.6, 1],
       [0.0, 1.0, 10.0, 0]], dtype=object)

### 데이터 세트 분리


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### 학습 (다중 선형 회귀)

In [6]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

### 예측 값과 실제 값 비교 (테스트 세트)

In [7]:
y_pred = reg.predict(X_test)
y_pred

array([ 92.15457859,  10.23753043, 108.36245302,  38.14675204])

In [8]:
y_test

array([ 90,   8, 100,  38], dtype=int64)

In [9]:
reg.coef_
# 집 도서관 (카페) 시간 결석
# 집에서하면 -5.8점 도서관 -1점 카페 0점 시간당 10점 결석당 -1.6점

array([-5.82712824, -1.04450647, 10.40419528, -1.64200104])

In [10]:
reg.intercept_

5.365006706544733

In [12]:
reg.score(X_train, y_train) # 훈련 셋

0.9623352565265528

In [13]:
reg.score(X_test, y_test) # 테스트 셋

0.9859956178877445

### 평가 지표 (회귀 모델)

1. MAE (Mean Absoulte Error) : (실제 값과 예측값) 차이의 절대 값 (의 평균)
2. MSE (Mean Squared Error) : 차이의 제곱
3. RMSE (Root Mean Squared Error) : 차이의 제곱에 루트
4. R2: 결정 계수
>> R2는 1에 가까울 수록, 나머지는 0에 가까울 수록 좋음

In [20]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# 실제 값, 예측 값
mean_absolute_error(y_test, y_pred)

3.225328518828811

In [17]:
mean_squared_error(y_test, y_pred)

19.90022698151514

In [18]:
mean_squared_error(y_test, y_pred, squared=False) # RMSE

4.460967045553591

In [21]:
r2_score(y_test, y_pred)
# 참고: Linear Regression .score()는 r2_score()이다

0.9859956178877445